
services:
  drupal: # name of the image
    image: drupal:9 # the actual version of the image
    ports: # assigned ports.  
      - "8080:80"
# I found these in docker hub in under the drupal image. This listed commonuse volumes.    
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=mypasswd
# you can use volumes by the name and not having anything in them like below
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
